basic cyclic lr implementation & documentation update
gnina/scripts pull request #10
Opened 2018-02-12 18:49 UTC by Ryo112358

Learning rate varying correctly, functioning as expected

2018-02-12 18:58 UTC, dkoes requested changes
Change it so you are cycling through multiples of the provided base_lr.  Set the multipliers such that with the default base_lr you get the current hardcoded values.

2018-02-12 18:58 UTC, dkoes commented on train.py
> +                elif args.cyclic:
These should be multiples of the base_lr instead of hardcoded values.

2018-02-13 16:02 UTC, Ryo112358 commented on train.py
> +                elif args.cyclic:
Made the change

2018-02-13 16:42 UTC, dkoes approved these changes

2018-02-13 16:42 UTC, merged