Fix evaluation for 'none' receptor
gnina/scripts pull request #32
Opened 2019-10-07 19:49 UTC by francoep

Made it so that if line contains none, we assume that the next token is for the ligand with:
'<rec>/<ligname>gninatypes'

Bails with Error message if the above check fails.

2019-10-07 19:50 UTC, francoep commented
Made it so that if line contains none, we assume that the next token is for the ligand with:
'\<rec\>/\<lig\>gninatypes'

2019-10-08 00:00 UTC, dkoes requested changes
I think there is an unnecessary check, but looks fine

2019-10-08 00:00 UTC, dkoes commented on affinity_search/evaluate.py
> +                if m is not None and m.group(2) is not None:
How can m.group(2) be None if m is not None?

2019-10-08 14:19 UTC, francoep commented
You are correct, fixed the if to be:

`if m in not None:`

2019-10-08 14:26 UTC, dkoes approved these changes

2019-10-08 14:26 UTC, merged